### ISSUE TITLE
Inclusion inside vim-terraform

### ISSUE THREAD

**Issue by pgporada** [jgerry/terraform-vim-folding#2]
@jgerry 

Would you like us, https://github.com/hashivim/vim-hashicorp-tools, to _fold_ your code into our project? I ask because we got a PR on one of our projects that contains your projects code. https://github.com/hashivim/vim-terraform/pull/17

**Comment by jgerry** [comment]
Sorry, I must have my email notifications turned off. Yes, I'd love to have this rolled in with the rest of the hashicorp tools.

**Comment by pgporada** [comment]
:D I'll get your code folded in ;)

On Apr 26, 2017 7:59 AM, "Jason Gerry" <notifications@github.com> wrote:

Sorry, I must have my email notifications turned off. Yes, I'd love to have
this rolled in with the rest of the hashicorp tools.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jgerry/terraform-vim-folding/issues/2#issuecomment-297380062>,
or mute the thread
